### ISSUE TITLE
Start animation thru console 

### ISSUE THREAD

**Issue by galoti** [TheCahyag/MinecraftAnimation#10]
Hello!!! Could you add the possibility to run the /start, /stop and /animate on console ? I need this to auto start animations with cmdscheduler plugin

**Comment by TheCahyag** [comment]
I'm very busy this week but I will expand on my thoughts relating to this enhancement sometime this weekend. Stay tuned or feel free to give any additional information on how you think this would work best for you.

**Comment by galoti** [comment]
Ok, thanks. 👍

**Comment by TheCahyag** [comment]
## Description
Provide (or modify) a set of commands accessible from the console that allows for starting, stopping and pausing animations.  
  
**Note:** I have chosen to leave out the ability to modify the settings of an animation since these should probably be changed prior to starting/stopping the animation from the console, or you should use the ability to specify certain settings in the start command. See the [command description wiki](https://github.com/TheCahyag/MinecraftAnimation/wiki/Command-Descriptions#animate-start-name--fnum--dnum--cnum) for more details.
### Additional Issue Notes
Test this alongside cmdscheduler.
## Implementation Details
This should only require additional checks when the command source is being detected. Additionally, I’m going to lump in the refactor for removing the run method that is overriding implementation in the AbstractCommand superclass.
## Test Cases
**Given:** An animation, test_animation, that is present with a non-zero number of frames with content.

* 1 - Start/stop/pause the test_animation in the console while a person is present to load the chunks that the animation occupies.
* 2 - Start/stop/pause the test_animation in the console while a person is present to load the chunks that the animation occupies. Then have a person load in to see if the animation is playing.
    * Make sure there aren’t any errors relating to changing blocks in chunks that aren’t loaded.
* 3 - Start/stop/pause the test_animation in the console and have a person in the game start or stop the animation
* 4 - Ensure the cmdscheduler’s console commands interact in the same manner as if typed in by a player
  
@galoti First and foremost, thanks for making a feature request. I have a lot of other things planned (as seen in the [projects page](https://github.com/TheCahyag/MinecraftAnimation/projects)), but tbh it's other people making feature requests that motivate me to work on this haha. But besides that, how does this sound for what you're looking for?

**Comment by galoti** [comment]
That's great! I never had that much attention in a git issue before lol... Sounds good, with this my cassino sign will be finally auto on server start

**Comment by TheCahyag** [comment]
@galoti That sounds super awesome, if you get the chance you should totally upload a video of the sign. I always love seeing what other people do with the Animations plugin.

**Comment by 02Miki** [comment]
Hey, any news on this?

**Comment by TheCahyag** [comment]
It's still a work in progress. I shelved it awhile ago to focus on classes. I'm currently in crunch mode to finish up my degree in these next few weeks, perhaps I'll be able to revisit this in a month or two.

**Comment by adri88g** [comment]
Hey how is the project going?

**Comment by TheCahyag** [comment]
The project in general? Or this particular issue?

I'll answer the former as it will be a more informative answer. To my disappointment, most major feature enhancing developments stopped in 2018. I've kept up with bugs in the meantime and I wish I had more of a drive to continually develop the [vast number of features](https://github.com/TheCahyag/MinecraftAnimation/blob/sponge-api/7/TODO.md) I really had hoped to get to. I could go on and on about why this is and all the reasons I tell myself as to why I was held back from spending lots of time on this, but ultimately it just kept dropping down on the list of projects I wanted to work on and real life took over. As a follow-up to my previous comment from 4/14/20, I did end up finishing college and getting a job, so that's great.

I didn't feel super bad about not doing much with the project as it wasn't super widespread nor essential (just looks nice) and the state I had left it in was somewhat solid.

From the outside looking in the project seems pretty dead and I'd be repeating past mistakes by saying I'd work on it in a few months only to kick the can down the road... I was developing this right before Sponge came out with their Ore system of listing plugins and I never quite got my plugin in there (Not to mention all the breaking changes that are soon coming from API 8). I wanted to rework the plugin when they implemented their new command-line system, thinking that was just around the corner. That was 2+ years ago haha.. At this point, I'm just rambling...

I wouldn't at all mind help from outside sources, but my time is limited with these kinds of passion projects. Maybe at a future date my drive for this will change but I'm not here to make any promises or to lay out a roadmap only to disappoint later on. Hopefully, you've gathered something from this rather unstructured monologue thanks for your interest and just reaching out to see how things are, kind stranger.

**Comment by TheCahyag** [comment]
@galoti Sorry this took so long, but starting and stopping the animations is now possible via the console. I've added this in release 0.4.0 https://github.com/TheCahyag/MinecraftAnimation/releases/tag/0.4.0
Usage:
/animate start <animation_name> <animation_owner_uuid>
/animate stop <animation_name> <animation_owner_uuid>
