### ISSUE TITLE
Animations don't work

### ISSUE THREAD

**Issue by 02Miki** [TheCahyag/MinecraftAnimation#12]
This is the error I'm getting:
https://pastebin.com/keiXnV9f

**Comment by TheCahyag** [comment]
Thanks for submitting this bug. Could you provide a database file containing the animation that is causing this error? This file will be under the Animations folder under your mods directory.

**Comment by 02Miki** [comment]
[ANIMATIONS.mv.zip](https://github.com/TheCahyag/MinecraftAnimation/files/4477564/ANIMATIONS.mv.zip)

**Comment by TheCahyag** [comment]
@02Miki Could I have your Minecraft user name and the name of the animation you created that's giving you this issue? 

Edit: As well as the version of Sponge you are using.

**Comment by 02Miki** [comment]
02Miki and test1, test. Every animation we try to create just doesn't work, even w other igns etc
running spongeforge 1.12.2-2768-7.1.6-RC3616

**Comment by TheCahyag** [comment]
I'm creating a fix right now, I was able to reproduce the issue (which may or may not be the exact issue you are experiencing). After creating an animation and setting the two corners, you can create frames, but when you create those you need to update the frames `/animate test frame update frame0`, or update the frame via the button UPDATE button on the given frame. I believe this issue is caused when you try to start an animation that has zero frames with content. Created frames don't automatically have content. In the meantime check out this wiki page https://github.com/TheCahyag/MinecraftAnimation/wiki/Basic-Usage

**Comment by TheCahyag** [comment]
This did illuminate a flaw in my error checking, so I'm glad you were able to point that out to me. Otherwise, it looks like you just need to add content to your frames via the update button. There is release 0.3.2 that addresses this issue https://github.com/TheCahyag/MinecraftAnimation/releases/tag/0.3.2

**Comment by 02Miki** [comment]
what? already fixed? this fast, god! Ty
